/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.carrerahilos_ortizmunozpablo;


import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JProgressBar;

/**
 *
 * @author alumno
 */
public class carrera_OrtizMunozPablo extends javax.swing.JFrame {

     private JLabel dorado, negro, rojo, verde;
    
    // Declaramos las barras de progreso
    private JProgressBar barraDorado, barraNegro, barraRojo, barraVerde;
    
    public carrera_OrtizMunozPablo() {
        initComponents();
         // Inicializamos los JLabel para los coches
        this.setLayout(null);  // Desactivar el layout para poder usar setBounds
        
        // Inicializar los JLabel para los coches
        dorado = new JLabel(new ImageIcon("../../../resources/dorado.png"));
        negro = new JLabel(new ImageIcon("../../../resources/negro.png"));
        rojo = new JLabel(new ImageIcon("../../../resources/rojo.png"));
        verde = new JLabel(new ImageIcon("../../../resources/verde.png"));
        
        // Posicionar los coches
        dorado.setBounds(50, 50, 100, 50);
        negro.setBounds(50, 150, 100, 50);
        rojo.setBounds(50, 250, 100, 50);
        verde.setBounds(50, 350, 100, 50);
        
        // Inicializar las barras de progreso
        barraDorado = new JProgressBar();
        barraNegro = new JProgressBar();
        barraRojo = new JProgressBar();
        barraVerde = new JProgressBar();
        
        // Configurar las barras de progreso
        barraDorado.setBounds(200, 50, 800, 20);
        barraNegro.setBounds(200, 150, 800, 20);
        barraRojo.setBounds(200, 250, 800, 20);
        barraVerde.setBounds(200, 350, 800, 20);
        
        // Agregar la imagen de fondo
        ImageIcon fondo = new ImageIcon("../../../resources/carrera.png");
        JLabel labelFondo = new JLabel(fondo);
        labelFondo.setBounds(0, 0, this.getWidth(), this.getHeight());
        panel1.add(labelFondo);  // Agregar fondo al panel
        
        // Agregar los coches y las barras de progreso después del fondo
        panel1.add(dorado);
        panel1.add(negro);
        panel1.add(rojo);
        panel1.add(verde);
        panel1.add(barraDorado);
        panel1.add(barraNegro); 
        panel1.add(barraRojo);
        panel1.add(barraVerde);
        panel1.repaint();
        
        // Crear y lanzar los hilos
        Thread hiloDorado = new Thread(new carrera(barraDorado, dorado));
        Thread hiloNegro = new Thread(new carrera(barraNegro, negro));
        Thread hiloRojo = new Thread(new carrera(barraRojo, rojo));
        Thread hiloVerde = new Thread(new carrera(barraVerde, verde));
        
        hiloDorado.start();
        hiloNegro.start();
        hiloRojo.start();
        hiloVerde.start();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(carrera_OrtizMunozPablo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(carrera_OrtizMunozPablo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(carrera_OrtizMunozPablo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(carrera_OrtizMunozPablo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new carrera_OrtizMunozPablo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panel1;
    // End of variables declaration//GEN-END:variables
}
